apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-deployment
spec:
  # Задаётся кол-во реплик контейнера, из параметра template,
  # который описывает контейнер ниже.
  replicas: 5
  selector:
    matchLabels:
      components: frontend
    # Шаблон пода
  template:
    # По сути это копия metadata из файла pod.yml без name
    metadata:
      labels:
        components: frontend
    spec:
      containers:
        - name: short-app
          image: antonlarichev/short-app:v1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m" # полная загрузка, 500m - 50%, 250M - 25%, 125 - 12,5%, 100 - 10%