apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-app-deployment
spec:
  # Задаётся кол-во реплик контейнера, из параметра template,
  # который описывает контейнер ниже.
  replicas: 1
  selector:
    matchLabels:
      components: frontend
    # Шаблон пода
  template:
    # По сути это копия metadata из файла pod.yml без name
    metadata:
      labels:
        components: frontend
    spec:
      containers:
        - name: conv-app
          image: antonlarichev/conv-app:1.2
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1028Mi"
              cpu: "300m" # полная загрузка, 500m - 50%, 250M - 25%, 125 - 12,5%, 100 - 10%