apiVersion: v1
kind: Secret
metadata:
  name: rmq-secret
type: Opaque
data:
  SEED_USERNAME: ZGVtbw== # demo - прописываем логин в rmq
  SEED_USER_PASSWORD: ZGVtbw== # demo - прописываем пароль в rmq
  AMQP_EXCHANGE: dGVzdA== # test - наименование общего хранилища данных
  AMQP_USER: ZGVtbw== # Имя польз., для подключения кластера api.
  AMQP_PASSWORD: ZGVtbw== # Пароль польз., для подключения кластера api.
  AMQP_HOSTNAME: cm1xLWNsdXN0ZXJpcA== # rmq-clusterip - адрес хоста (имя ClusterIP rabbitmq), для подключения conv-api

