app:
  name: conv-app
  image: setter2000/conv-app
  version: "1.1"
  components: frontend
  port: 80
  host: "conv.test"
  replicas: 1
  path: "/"
  limits:
    memory: "400Mi"
    cpu: "200m" # полная загрузка, 500m - 50%, 250M - 25%, 125 - 12,5%, 100 - 10%
  envs:
    - VITE_DOMAIN

api:
  name: conv-api
  image: antonlarichev/conv-api
  version: "1.0"
  components: backend
  port: 3000
  host: conv.test
  replicas: 1
  path: "/api"
  limits:
    memory: "500Mi"
    cpu: "200m"
  envs:
    - AMQP_USER     # Логин для подключения к RabbitMQ.
    - AMQP_PASSWORD # Пароль для подключения к RabbitMQ.
    - AMQP_HOSTNAME # Хост для подключения к RabbitMQ.
    - AMQP_EXCHANGE # Хранилище общее.
    - AMQP_QUEUE    # Очередь для RabbitMQ.

rmq:
  name: rmq
  image: rabbitmq
  version: 3.12.7-management
  components: rmq
  port: 5672
  limits:
    memory: "500Mi"
    cpu: "300m"
  envs:
    - RABBITMQ_DEFAULT_USER
    - RABBITMQ_DEFAULT_PASS

database:
  user: demo       # demo - логин в rmq
  password: demo   # demo - пароль в rmq
  exchange: test   # test - общее хранилище данных
  queue: converter # converter - очередь

service:
  name: conv-service
  image: antonlarichev/conv-service
  version: "1.0"
  components: backend
  port: 3000
  host: conv.test
  replicas: 1
  limits:
    memory: "500Mi"
    cpu: "200m"
  envs:
    - AMQP_USER     # Логин для подключения к RabbitMQ.
    - AMQP_PASSWORD # Пароль для подключения к RabbitMQ.
    - AMQP_HOSTNAME # Хост для подключения к RabbitMQ.
    - AMQP_EXCHANGE # Хранилище общее.
    - AMQP_QUEUE    # Очередь для RabbitMQ.
