apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.app.host}}
      http:
        paths:
          - pathType: {{.Values.app.pathType | title}}
            path: {{.Values.app.path}}
            backend:
              service:
                name: "{{.Values.app.name}}-clusterip"
                port:
                  number: {{.Values.app.port}}
          - pathType: {{.Values.app.pathType | title}}
            path: {{.Values.api.path}}
            backend:
              service:
                name: "{{.Values.app.name}}-clusterip"
                port:
                  number: {{.Values.api.port}}
