apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.rmq.name}}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      components: {{.Values.rmq.components}}
  template:
    metadata:
      labels:
        components: {{.Values.rmq.components}}
    spec:
      containers:
        - name: {{.Values.rmq.name}}
          image: "{{.Values.rmq.image}}:{{.Values.rmq.version}}"
          ports:
            - containerPort: {{.Values.rmq.port}}
          env:
          {{- range .Values.rmq.envs }}
          {{- $data := dict "name" $.Values.rmq.name "env" . }}
          {{- include "env.template" $data | indent 12 }}
          {{- end }}
          resources:
            limits: {{.Values.app.limits | toYaml | nindent 15}}
          volumeMounts:
            - name: "{{.Values.rmq.name}}-data"
              mountPath: /var/lib/rabbitmq/data
              subPath: {{.Values.rmq.name}}
      volumes:
        - name: "{{.Values.rmq.name}}-data"
          persistentVolumeClaim:
            claimName: "{{.Values.rmq.name}}-pvc"
